-- ==============================================================================
-- BUS SAHAYI (BUS സഹായി) - CLEAN DATABASE REGENESIS & RLS POLICIES
-- Drops pre-existing prototype tables and initializes full production architecture.
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ------------------------------------------------------------------------------
-- 0. CLEANUP EXISTING TABLES (CASCADE)
-- ------------------------------------------------------------------------------
DROP TABLE IF EXISTS public.activity_logs CASCADE;
DROP TABLE IF EXISTS public.escalation_events CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.action_tokens CASCADE;
DROP TABLE IF EXISTS public.complaint_history CASCADE;
DROP TABLE IF EXISTS public.complaint_images CASCADE;
DROP TABLE IF EXISTS public.complaints CASCADE;
DROP TABLE IF EXISTS public.duty_assignments CASCADE;
DROP TABLE IF EXISTS public.conductors CASCADE;
DROP TABLE IF EXISTS public.route_stops CASCADE;
DROP TABLE IF EXISTS public.routes CASCADE;
DROP TABLE IF EXISTS public.buses CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.depots CASCADE;

-- ------------------------------------------------------------------------------
-- 1. DEPOTS TABLE (KSRTC 97 Depots Master Dataset - IDs 1..97)
-- ------------------------------------------------------------------------------
CREATE TABLE public.depots (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    depot_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    mobile TEXT,
    head_phone TEXT,
    email TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 2. PROFILES TABLE (Linked to Supabase auth.users & integer depot_id)
-- ------------------------------------------------------------------------------
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    auth_user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    role TEXT NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'DEPOT_HEAD', 'ADMIN')),
    depot_id INT REFERENCES public.depots(id) ON DELETE SET NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 3. BUSES TABLE (KSRTC Bus Fleet Master Data)
-- ------------------------------------------------------------------------------
CREATE TABLE public.buses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus_number TEXT NOT NULL,
    registration_number TEXT NOT NULL UNIQUE,
    depot_id INT REFERENCES public.depots(id) ON DELETE CASCADE,
    bus_type TEXT DEFAULT 'Super Fast',
    status TEXT DEFAULT 'ACTIVE',
    data_source TEXT DEFAULT 'MOCK',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 4. ROUTES TABLE (KSRTC Bus Routes Master Data)
-- ------------------------------------------------------------------------------
CREATE TABLE public.routes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_code TEXT NOT NULL UNIQUE,
    source TEXT NOT NULL,
    destination TEXT NOT NULL,
    depot_id INT REFERENCES public.depots(id) ON DELETE CASCADE,
    estimated_duration TEXT,
    status TEXT DEFAULT 'ACTIVE',
    data_source TEXT DEFAULT 'MOCK',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 5. ROUTE STOPS TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE public.route_stops (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id INT REFERENCES public.routes(id) ON DELETE CASCADE,
    stop_name TEXT NOT NULL,
    stop_sequence INT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 6. CONDUCTORS TABLE (KSRTC Staff Master Data)
-- ------------------------------------------------------------------------------
CREATE TABLE public.conductors (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pen TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    depot_id INT REFERENCES public.depots(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'ACTIVE',
    data_source TEXT DEFAULT 'MOCK',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 7. DUTY ASSIGNMENTS TABLE (Bus + Route + Conductor Shifts)
-- ------------------------------------------------------------------------------
CREATE TABLE public.duty_assignments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus_id INT REFERENCES public.buses(id) ON DELETE CASCADE,
    route_id INT REFERENCES public.routes(id) ON DELETE CASCADE,
    conductor_id INT REFERENCES public.conductors(id) ON DELETE CASCADE,
    depot_id INT REFERENCES public.depots(id) ON DELETE CASCADE,
    duty_date DATE NOT NULL DEFAULT CURRENT_DATE,
    shift_start TIME NOT NULL,
    shift_end TIME NOT NULL,
    trip_number INT DEFAULT 1,
    status TEXT DEFAULT 'ASSIGNED',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 8. COMPLAINTS TABLE (UUID Identifier Core Grievance Record)
-- ------------------------------------------------------------------------------
CREATE TABLE public.complaints (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reference_number TEXT NOT NULL UNIQUE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    depot_id INT REFERENCES public.depots(id) ON DELETE SET NULL,
    bus_id INT REFERENCES public.buses(id) ON DELETE SET NULL,
    route_id INT REFERENCES public.routes(id) ON DELETE SET NULL,
    category TEXT NOT NULL,
    other_category TEXT,
    description TEXT NOT NULL,
    location_name TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    reported_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT NOT NULL DEFAULT 'SUBMITTED' CHECK (status IN ('SUBMITTED', 'ASSIGNED', 'UNDER_REVIEW', 'ACTION_TAKEN', 'UNABLE_TO_RESOLVE', 'RESOLVED', 'REJECTED', 'ESCALATED', 'ACTION_REQUIRED')),
    priority TEXT DEFAULT 'NORMAL',
    assigned_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 9. COMPLAINT IMAGES TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE public.complaint_images (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    complaint_id UUID REFERENCES public.complaints(id) ON DELETE CASCADE,
    storage_path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    mime_type TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 10. COMPLAINT HISTORY TABLE (Audit Log / Status Timeline)
-- ------------------------------------------------------------------------------
CREATE TABLE public.complaint_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    complaint_id UUID REFERENCES public.complaints(id) ON DELETE CASCADE,
    old_status TEXT,
    new_status TEXT NOT NULL,
    changed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    changed_by_role TEXT,
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 11. ACTION TOKENS TABLE (Secure Conductors SMS Action Links)
-- ------------------------------------------------------------------------------
CREATE TABLE public.action_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    complaint_id UUID REFERENCES public.complaints(id) ON DELETE CASCADE,
    conductor_id INT REFERENCES public.conductors(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 12. NOTIFICATIONS TABLE (Twilio SMS Log & Delivery Tracking)
-- ------------------------------------------------------------------------------
CREATE TABLE public.notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    complaint_id UUID REFERENCES public.complaints(id) ON DELETE SET NULL,
    recipient_type TEXT NOT NULL,
    recipient_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    notification_type TEXT NOT NULL,
    channel TEXT DEFAULT 'SMS',
    actual_recipient TEXT NOT NULL,
    title TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'PENDING',
    provider TEXT DEFAULT 'TWILIO',
    provider_message_id TEXT,
    failure_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    sent_at TIMESTAMPTZ
);

-- ------------------------------------------------------------------------------
-- 13. ESCALATION EVENTS TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE public.escalation_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    complaint_id UUID REFERENCES public.complaints(id) ON DELETE CASCADE,
    escalated_from_depot_id INT REFERENCES public.depots(id) ON DELETE CASCADE,
    reason TEXT NOT NULL,
    status TEXT DEFAULT 'OPEN',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);

-- ------------------------------------------------------------------------------
-- 14. ACTIVITY LOGS TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE public.activity_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    resource_type TEXT,
    resource_id UUID,
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- AUTOMATIC PROFILE CREATION TRIGGER FOR SUPABASE AUTH SIGNUPS
-- ==============================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (auth_user_id, name, phone, email, role, active)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'name', NEW.phone, NEW.email, 'User'),
        COALESCE(NEW.phone, NEW.raw_user_meta_data->>'phone', ''),
        COALESCE(NEW.email, CONCAT('user_', SUBSTRING(NEW.id::text, 1, 8), '@bussahayi.org')),
        COALESCE(UPPER(NEW.raw_user_meta_data->>'role'), 'USER'),
        TRUE
    )
    ON CONFLICT (auth_user_id) DO UPDATE SET
        name = EXCLUDED.name,
        phone = EXCLUDED.phone,
        email = EXCLUDED.email;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- BACKFILL PROFILES FOR EXISTING AUTH USERS
INSERT INTO public.profiles (auth_user_id, name, phone, email, role)
SELECT 
    id,
    COALESCE(raw_user_meta_data->>'name', phone, email, 'User'),
    COALESCE(phone, raw_user_meta_data->>'phone', ''),
    COALESCE(email, CONCAT('user_', SUBSTRING(id::text, 1, 8), '@bussahayi.org')),
    COALESCE(UPPER(raw_user_meta_data->>'role'), 'USER')
FROM auth.users
ON CONFLICT (auth_user_id) DO NOTHING;

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================

ALTER TABLE public.depots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.route_stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conductors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.duty_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaint_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaint_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.action_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.escalation_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- PUBLIC READ POLICIES (Master Data)
CREATE POLICY "Allow public read access to depots" ON public.depots FOR SELECT USING (true);
CREATE POLICY "Allow public read access to buses" ON public.buses FOR SELECT USING (true);
CREATE POLICY "Allow public read access to routes" ON public.routes FOR SELECT USING (true);
CREATE POLICY "Allow public read access to route_stops" ON public.route_stops FOR SELECT USING (true);

-- PROFILES RLS
CREATE POLICY "Users view own profile" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users insert own profile" ON public.profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE USING (true);

-- COMPLAINTS RLS
CREATE POLICY "Users view own complaints" ON public.complaints FOR SELECT USING (true);
CREATE POLICY "Users create complaints" ON public.complaints FOR INSERT WITH CHECK (true);

CREATE POLICY "Depot heads view assigned complaints" ON public.complaints FOR SELECT USING (
    depot_id IN (
        SELECT depot_id FROM public.profiles 
        WHERE auth_user_id = auth.uid() AND role = 'DEPOT_HEAD'
    )
);

CREATE POLICY "Depot heads update assigned complaints" ON public.complaints FOR UPDATE USING (
    depot_id IN (
        SELECT depot_id FROM public.profiles 
        WHERE auth_user_id = auth.uid() AND role = 'DEPOT_HEAD'
    )
);

CREATE POLICY "Admins full access to complaints" ON public.complaints FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE auth_user_id = auth.uid() AND role = 'ADMIN'
    )
);

-- AUTOMATIC UPDATED_AT TRIGGER FUNCTION
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_profiles_modtime
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER update_complaints_modtime
    BEFORE UPDATE ON public.complaints
    FOR EACH ROW EXECUTE FUNCTION update_timestamp();
