import type { SystemMetrics, TrendPoint, CategoryDistribution, DepotWorkload, RecurringIssueAlert } from '../types/analytics';
import { apiRequest } from './api';
import { fetchComplaints } from './complaintsService';

export async function fetchSystemMetrics(): Promise<SystemMetrics> { const data = await apiRequest<any>('/admin/dashboard'); const total = data.total_complaints || 0; const resolved = data.resolved || 0; return { totalComplaints: total, openComplaints: data.pending || total - resolved, resolvedToday: resolved, overdueCount: data.escalated || 0, criticalCount: 0, avgResolutionTimeHours: 0, slaComplianceRate: total ? Math.round(resolved * 100 / total) : 100 }; }

export async function fetchDepotWorkload(): Promise<DepotWorkload[]> { const rows = await apiRequest<any[]>('/admin/depots/map'); return rows.map((row) => ({ depotId: String(row.depot_id), depotName: row.name, open: row.pending, overdue: row.escalated, resolvedThisWeek: row.resolved, slaCompliance: row.resolution_rate })); }

async function allComplaints() { const result = await apiRequest<any>('/admin/complaints?per_page=1000'); return (result.complaints || []) as any[]; }
export async function fetchCategoryDistribution(): Promise<CategoryDistribution[]> { const rows = await allComplaints(); const counts = new Map<string, number>(); rows.forEach((row) => counts.set(row.category, (counts.get(row.category) || 0) + 1)); const total = rows.length || 1; return Array.from(counts.entries()).map(([category, count], index) => ({ category: category.toLowerCase(), label: category, count, percentage: Math.round(count * 100 / total), color: ['#D92D20', '#F59E0B', '#3B82F6', '#16A34A', '#8B5CF6', '#6B7280'][index % 6] })); }
export async function fetchTrendData(): Promise<TrendPoint[]> { const rows = await allComplaints(); const byDay = new Map<string, TrendPoint>(); rows.forEach((row) => { const date = new Date(row.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }); const point = byDay.get(date) || { date, submitted: 0, resolved: 0, escalated: 0 }; point.submitted += 1; if (row.status === 'RESOLVED') point.resolved += 1; if (row.status === 'ESCALATED') point.escalated += 1; byDay.set(date, point); }); return Array.from(byDay.values()).slice(-14); }
export async function fetchRecurringIssueAlerts(): Promise<RecurringIssueAlert[]> { const rows = await fetchComplaints({}); const grouped = new Map<string, number>(); rows.forEach((row) => { const key = `${row.routeCode || row.routeFrom || 'Unknown route'}|${row.category}`; grouped.set(key, (grouped.get(key) || 0) + 1); }); return Array.from(grouped.entries()).filter(([, count]) => count > 1).map(([key, count], index) => { const [routeName, category] = key.split('|'); return { id: `alert-${index}`, routeId: routeName, routeName, busNumber: '', category, categoryLabel: category, count, timeWindow: 'Current dataset', assignedDepot: '', evidenceSummary: `${count} complaints in the backend dataset.`, status: 'active', severity: count > 5 ? 'critical' : 'high' }; }); }
